// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhiopcgwhmpssjiyirin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoaW9wY2d3aG1wc3NqaXlpcmluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzI2OTksImV4cCI6MjA2Mzg0ODY5OX0.IIbGvl0uk-z6g5gaqrmoMCjS2of9DKBY71jcFQKitq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);